### ISSUE TITLE
exception:org.dom4j.DocumentException: Error on line 1 of document  : Content is not allowed in prolog. Nested exception: Content is not allowed in prolog.

### ISSUE THREAD

**Issue by yugansh20** [yavijava/yavijava#121]
Hi,

I am trying to get some ESX server info and getting this exception for some servers while logging in.

---------------Stack Trace----------------------
 Failed with  VI SDK invoke exception:-Org.d...
 Failed with  VI SDK invoke exception:org.dom4j.DocumentException: Error on line 1 of document  : Content is not allowed in prolog. Nested exception: Content is not allowed in prolog.
java.rmi.RemoteException: VI SDK invoke exception:org.dom4j.DocumentException: Error on line 1 of document  : Content is not allowed in prolog. Nested exception: Content is not allowed in prolog.
    at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:76)
    at com.vmware.vim25.ws.SoapClient.unMarshall(SoapClient.java:203)
    at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:96)
    at com.vmware.vim25.ws.VimStub.retrieveServiceContent(VimStub.java:1665)
    at com.vmware.vim25.mo.ServiceInstance.<init>(ServiceInstance.java:85)
##     at com.vmware.vim25.mo.ServiceInstance.<init>(ServiceInstance.java:69)

-----------Code Snippet------------------
        String url = "abc"
        String user = "xyz";
        String password = "xyz";
##                 ServiceInstance serviceInstance = new ServiceInstance(new URL(url), user, password,true);

VERSION :
yavijava - 5.5.10
dom4j - 1.6.1

**Comment by michaelrice** [comment]
Hello @yugansh20 can you upgrade to the current 6.x release and enable debug logging and provide that output for us? Please take care to remove any passwords from the XML before you share that output with us.

**Comment by yugansh20** [comment]
Here are the logs - 

 TRACE WSClient:69 - Creating WSClient to server URL: https://xyz/sdk
 TRACE WSClient:70 - Ignore ssl: true
 TRACE WSClient:89 - Invoking method: RetrieveServiceContent
 TRACE SoapClient:190 - Marshalled Payload String xml: <?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">soapenv:Body<RetrieveServiceContent xmlns="urn:vim25"><_this type="ServiceInstance">ServiceInstance</_this></RetrieveServiceContent>/soapenv:Body/soapenv:Envelope
TRACE WSClient:188 - POST: null
TRACE WSClient:189 - Payload: <?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">soapenv:Body<RetrieveServiceContent xmlns="urn:vim25"><_this type="ServiceInstance">ServiceInstance</_this></RetrieveServiceContent>/soapenv:Body/soapenv:Envelope
 DEBUG WSClient:245 - Caught an IOException. Reading ErrorStream for results.
 java.io.IOException: Server returned HTTP response code: 400 for URL: https://xyz/sdk
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
    at com.vmware.vim25.ws.WSClient.post(WSClient.java:241)
    at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:94)
    at com.vmware.vim25.ws.VimStub.retrieveServiceContent(VimStub.java:1665)
    at com.vmware.vim25.mo.ServiceInstance.<init>(ServiceInstance.java:85)
    at com.vmware.vim25.mo.ServiceInstance.<init>(ServiceInstance.java:69)

**Comment by yugansh20** [comment]
I have tried it with 6.x release and facing same problem

**Comment by dsharma1** [comment]
Whats the issue here? I am also getting the same error? My namespace version is  xmlns="urn:vim25"> and vsphere version is 7.0

**Comment by talmoshe24** [comment]
Just found out that login to vc7 using Amazon Corretto\jre8 works for me!
Can't explain... I am using Java(TM) SE Runtime Environment (build 1.8.0_202-b08) to connect with the same code to vc 6.7 and it works.
