### ISSUE TITLE
Need help on "ServiceInstance" ignoreCert parameter. 

### ISSUE THREAD

**Issue by vThinkBeyondVM** [yavijava/yavijava#127]
I am not sure if this the right place to ask this question. 

ServiceInstance si = new ServiceInstance(new URL(
                "https://10.10.1.2./sdk"), "administrator@vsphere.local",
                "Administrator!23", true);

As you could see in above code, ServiceInstance constructor takes third parameter as "ignoreCert" and I have set it as "TRUE". Now I would like to make my code work when I set this up as "FALSE". 

I have been trying but I could not get success. Can you please post one sample that can help to get this work? 

Your help would be  much appreciated.

**Comment by michaelrice** [comment]
Setting it to false has nothing to do with the actual code base, so I cant provide a sample for you. You need to import your cert into your keystore if its not provided by a trusted CA, I would suggest using a trusted CA if you can, but if you have to use self signed, or something your internal company handles, then you are stuck having to import the cert into your keystore.

Good luck!

**Comment by michaelrice** [comment]
Here is a link that may help you http://stackoverflow.com/questions/11617210/how-to-properly-import-a-selfsigned-certificate-into-java-keystore-that-is-avail

**Comment by vThinkBeyondVM** [comment]
Thanks Michael for quick response.
