### ISSUE TITLE
Exception caught trying to invoke method RetrieveServiceContent : works with VI JAVA but NOT with YA VIJAVA

### ISSUE THREAD

**Issue by vThinkBeyondVM** [yavijava/yavijava#128]
Hi YA VIJAVA users,

Today I deployed latest YA VIJAVA in my Maven project. My program renames the VM in the VC inventory. 

When I run my program I get this error on VC 6.0

Exception in thread "main" java.rmi.RemoteException: Exception caught trying to invoke method RetrieveServiceContent; nested exception is: 
    javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative names matching IP address 10.x.x.x found
    at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:92)
    at com.vmware.vim25.ws.VimStub.retrieveServiceContent(VimStub.java:1667)
    at com.vmware.vim25.mo.ServiceInstance.<init>(ServiceInstance.java:83)
    at com.vmware.vim25.mo.ServiceInstance.<init>(ServiceInstance.java:69)​

VC that I am using is added to the domain (static IP is used)

When I run the same program from my old VI JAVA libraries on same 60 VC, it works just fine. I tried YA VIJAVA on my other 60 VC (which is not added to the domain and takes DHCP IP) and YA VIJAVA worked there.

I would like to know why is this happening. Why it works with old VI JAVA and Why it does not with YA VIJAVA. ?

**Comment by michaelrice** [comment]
What does your `ServiceInstance` line use for the `ignoreCert` param?

**Comment by vThinkBeyondVM** [comment]
Hi Michael,

I use "TRUE" for ignoreCert.

**Comment by michaelrice** [comment]
Please see #115 

Ive never been able to reproduce this, and we have tests that pass that check this issue. Read over the comments in #115 and see if you can help us come up with a way to reproduce this.
