### ISSUE TITLE
How do you get SSL thumbprint from vsphere server you are connected to

### ISSUE THREAD

**Issue by michaelrice** [yavijava/yavijava#130]
Need to find a way to grab the SSL thumbprint from the vsphere server you are connected to. For example if I connect to vCenter at myvcsa.vsphere.local how can I access its SSL thumbprint, same for an ESX/i server if connected directly to it instead of a vCenter.

**Comment by sharninder** [comment]
Does this work: http://www.virtuallyghetto.com/2012/04/extracting-ssl-thumbprint-from-esxi.html

I've used this method in the past for some projects.

**Comment by michaelrice** [comment]
Closed by #146
