### ISSUE TITLE
is 6.0.03 available on the Maven repository ?

### ISSUE THREAD

**Issue by vThinkBeyondVM** [yavijava/yavijava#136]
Hi Michael,

I just got your update on new version 6.0.03. I was checking in Maven central directory for the same here:http://mvnrepository.com/artifact/com.toastcoders/yavijava   but could not find the new entry.

Can you please let me know when it will be available on Maven so that I can update my project by adding this change in dependencies.?

**Comment by michaelrice** [comment]
Hello @vThinkBeyondVM 

The way maven releases work is that you push to sonatype which houses maven central. You have to first push to staging, once a package gets marked in staging as "release" there is a sync that takes place moving the package from sonatype staging to sonatype release. They claim this process can take up to 12 hours. Once it is in sonatype release it is available in maven central (find it at search.maven.org) any other repo you use is going to be a mirror of the main maven central, and a sync would need to take place before the new package is available at the mirror site. That is what is happening in your case. The mvnrespoitory.com site is a mirror and they may not have run their sync with maven central.

**Comment by vThinkBeyondVM** [comment]
OK. Got it. Thanks for your input.
