### ISSUE TITLE
TrustAllSSL.getTrustContext() not thread-safe

### ISSUE THREAD

**Issue by alawrenc** [yavijava/yavijava#144]
Hi Michael,

We discovered during product testing that opening connections to multiple vCenters very rapidly could cause a NPE on line 209 of WSClient.java. I haven't been able to reproduce it with a unit test, but adding a call to TrustAllSSL.getTrustContext() in a static initialization block prior to other usages of TrustAllSSL resolved the issue. From a quick code read, it appears possible to have 'alreadyCreated = true' prior to the sslContext being fully initialized.

Thanks!

**Comment by michaelrice** [comment]
I think this may have been addressed in #171 and fixed with the code from pull request #175 Please feel free to reopen this issue if that did not solve the problem
