### ISSUE TITLE
service instance initialisation using session cookie returns null

### ISSUE THREAD

**Issue by myelaman** [yavijava/yavijava#145]
public VSphereClient(String vCenterURL,
            String sessionStr) throws RemoteException, MalformedURLException {
        _logger.info("vCenterUrl adn Session Strings are" + vCenterURL
                + " " + sessionStr);
        String session = "vmware_soap_session=\"" + sessionStr + "\"";
        si = new ServiceInstance(new URL(vCenterURL), session, true);
    }

si throws a null pointer exception.Please fix this

**Comment by myelaman** [comment]
could you please comment on this issue

**Comment by michaelrice** [comment]
Thanks for submitting the issue.

**Comment by michaelrice** [comment]
This is not a bug. Please see #147 which adds a successful test showing this.
