### ISSUE TITLE
Maven repository

### ISSUE THREAD

**Issue by neil-greenwood** [yavijava/yavijava#15]
Hi,

Are any versions of this project available on a Maven repository? I can't find any on the central repo.

Many thanks,
Neil.

**Comment by michaelrice** [comment]
Hello @neil-greenwood right now there are not any versions of this on central maven. What I am doing internally is building manually with gradle and hosting it on our own artifactory. I do plan to spend a little bit of time one weekend soon to figure out what it takes to get it published on central maven.

**Comment by neil-greenwood** [comment]
Thanks for the update. I'm doing something similar for the moment.

**Comment by michaelrice** [comment]
Issue created to being process to get yavijava added to maven central https://issues.sonatype.org/browse/OSSRH-12303
