### ISSUE TITLE
java.lang.IllegalAccessException: Class com.vmware.vim25.ws.XmlGenDom can not access a member of class java.util.Calendar with modifiers "protected"

### ISSUE THREAD

**Issue by kbrowder** [yavijava/yavijava#153]
So I have a jetty webapp that tries to login to vsphere and it gets the following error:

```
java.rmi.RemoteException: Exception in SoapClient.invoke:; nested exception is:
java.lang.IllegalAccessException: Class com.vmware.vim25.ws.XmlGenDom can not access a member of class java.util.Calendar with modifiers "protected"
```

sorry no trace yet, I'll try and make one soon (or if I figure out the issue I'll file a MR).  Anyways I'm using the latest version of yavijava deployed to central (although older versions seem to have this problem as well) and JDK 7 and JDK8.  Again I'm running in jetty which i suppose could be the issue (somewhat more picky about accessing protected members?)

**Comment by michaelrice** [comment]
Please keep me posted on this. I have never run this lib on a jetty system, only tomcat, and have never run into this issue. Logs, and a full stacktrace would help too.

**Comment by kbrowder** [comment]
So I am rather delayed on getting back to this, sorry about that.  However what's a bit surprising is that it works on tomcat, specifically [java.util.Calendar](https://docs.oracle.com/javase/7/docs/api/java/util/Calendar.html#constructor_summary) has two protected constructors, however XmlGenDom.fromXml calls `clazz.newInstance()`  but should instead be doing:

```
Constructor constuctor = clazz.getDeclaredConstructor()
constructor.setAccessable(true)
constructor.newInstance()
```

Anyways at least that's my current chain of reasoning, I still plan on trying to make a minimized test-case to reproduce this issue.

Apologies again for the crazy delay on following up, I should have some more cycles to poke at this now(ish).

**Comment by kbrowder** [comment]
further updates:
- this happened after yavijava version 5.5.07 (07 is fine 08 and greater isn't), there's no obvious difference that would cause this afaict.
- Seems to only be an issue in Jython servlets (maybe in things other than Jetty too?) so I guess there's some odd interaction there, I'll expect to make a minimal example in a few days, hopefully at that point I'll have a good idea what the root cause is.

**Comment by kbrowder** [comment]
So for some reason loading Jython (via ModjyServlet) seems to cause someCalendarClass.getPackage() to be a different object (although they have the same data) than a `final private static Package UTIL_PKG = Calendar.class.getPackage()` (in TypeUtil), I'm not exactly sure why, maybe a classloader is mucking things up?  I'm attempting to minimize my test case to determine the exact culprit.

That being said I belive changing TypeUtil.isBasicType solves the problem:

``` java
public static boolean isBasicType(Class<?> clazz) {
        Package pkg = clazz.getPackage(); // for primitive type like int, the pkg is null
        return pkg == null || LANG_PKG.pkgName.equals(pkg.pkgName) || UTIL_PKG.pkgName.equals(pkg.pkgName);
    }
```

(I suppose UTIL_PKG/LANG_PKG could be made a string in the first place)

Is this reasonable?

**Comment by michaelrice** [comment]
Does that change break the tests?

**Comment by kbrowder** [comment]
The tests all pass locally although I haven't tried the intTests since I don't have access on my current machine.  As you can see I filed a PR if you wanna have a look at what I think is the end result.

**Comment by michaelrice** [comment]
It may take me a while to merge the code because I no longer work in a vmware environment and wont have access to any equipment where I could set something up to do the testing I normally do. If a few other community members happen to chime in and +1 it before I am able to test it out I will merge it sooner. Maybe @scottmlaplante could chime in here?

**Comment by scottmlaplante** [comment]
Sure i can take a look today or this weekend.

**Comment by scottmlaplante** [comment]
Ive merged the code into my local environment and it doesn't seem to cause any problems. I will run the intTests next and update.

**Comment by scottmlaplante** [comment]
Ive run the intTests with this change without issue. Ill give my +1 to merge this in!

**Comment by michaelrice** [comment]
Thanks a bunch @scottmlaplante

**Comment by kbrowder** [comment]
Thanks to both of you!  Any idea when this will hit central?

**Comment by michaelrice** [comment]
Ive cut the release as of 5 mins ago and published to maven, Ive seen the sync process happen in as little as an hour and take as long as 24.

**Comment by kbrowder** [comment]
Got the release as of yesterday and my Jython code now works! Thanks again @michaelrice and @scottmlaplante for verifying and shipping this fix and for the fork of vijava in the first place.

**Comment by michaelrice** [comment]
@kbrowder and thank you for the patch!
