### ISSUE TITLE
Cannot cast ManagedEntity to VirtualApp

### ISSUE THREAD

**Issue by cnc3** [yavijava/yavijava#158]
When trying to walk back to the Datacenter from a VirtualMachine when the VirtualMachine is part of a VApp the getParentVApp() method appears to be returning a ManagedEntity and not a VirtualApp sub-class. Attempting to cast a ManagedEntity to a VirtualApp fails. This makes the getParentFolder() method of VirtualApp unavailable. getParent() works off the ManagedEntity but takes the resource pool/host path to the Datacenter and I would like the folder/vm path instead.

yavijava version 6.0.03. Java 7.

**Comment by michaelrice** [comment]
Can you provide the TRACE logging for the problem you are running into? Per the docs a `vm.getParentVApp()` should be returning a `ManagedEntity` as you say its doing. The `VirtualApp` extends a `ResourcePool` and that extends a `ManagedEntity`, so I would be curious to see the XML coming back from the server and such. I would run this myself but I am no longer in a role where I have ready access to a VMWare environment. If you are able to provide this logging please be sure to remove any passwords or things from the logging as it will have EVERYTHING in plain text.

Thanks!

**Comment by cnc3** [comment]
Re-reading the SDK specification makes me think that I cannot get there from here. Essentially, there does not seem to be a way to walk from a VirtualMachine contained in a VirtualApp to the Datacenter via the Folder path. Instead, you can only walk up using the ResourcePool path. That is, you can walk up to create a path of Datacenter/host/ResourcePool/VirtualApp/VirtualMachine but not Datacenter/vm/Folder/VirtualApp/VirtualMachine. (You can get the ../vm/Folder/.. path for a VirtualMachine that is not in a VirtualApp.)

I was fooled by the mob because you can walk down through ../vm/.. to the VirtualMachine.

So... not a code bug but a fault in my interpretation of the SDK.
