### ISSUE TITLE
Minor performance issue in XmlGenDom

### ISSUE THREAD

**Issue by mikebrazinski** [yavijava/yavijava#167]
I was debugging a local issue and I found a possible performance issue in the method fromXML in XmlGenDom.java. Line 80 is `log.trace("XML Document: " + doc.asXML());` This should be wrapped with `if ( log.isTraceEnabled ) {...}`. As is, the code is converting the document to string only to be ignored unless we're tracing at log level.

Thanks

**Comment by michaelrice** [comment]
Thanks @mikebrazinski
