### ISSUE TITLE
NullPointerException while getting the SSLContext

### ISSUE THREAD

**Issue by alex-lata** [yavijava/yavijava#171]
Hi,

Launching a _parallel_ query to multiple WSClients ends up with an NPE:
`Caused by: java.lang.NullPointerException
    at com.vmware.vim25.ws.WSClient.getTrustAllSocketFactory(WSClient.java:225)
    at com.vmware.vim25.ws.WSClient.<init>(WSClient.java:85)
    at com.vmware.vim25.ws.WSClient.<init>(WSClient.java:69)
    ... 23 more`
`2016-06-20 11:10:44,469 ERROR query                    : Task failed in daemon "query"
java.lang.NullPointerException
    at com.vmware.vim25.mo.ServiceInstance.constructServiceInstance(ServiceInstance.java:121)
    at com.vmware.vim25.mo.ServiceInstance.<init>(ServiceInstance.java:104)`

By looking at _TrustAllSSL.getTrustContext()_ method I guess that the 'problem' comes from the fact that the _setAlreadyCreated()_ call is done too early; Making the other threads 'think' that the context was already created, which is not the case.

Making the getTrustContext method synchronized could do the job, or maybe just delaying the   setAlreadyCreated() call. Any help would be appreciated! 

Here's my environment:
Java: 1.8.0_66-b17
yavijava: 6.0.04
vSphere: 6.0.0

Thanks!
Alex

**Comment by michaelrice** [comment]
Can you provide me with some sample code that reproduces your issue?

**Comment by alex-lata** [comment]
Hi,
Here's the sample code reproducing the issue:

``` java
import com.vmware.vim25.InvalidProperty;
import com.vmware.vim25.RuntimeFault;
import com.vmware.vim25.mo.InventoryNavigator;
import com.vmware.vim25.mo.ManagedEntity;
import com.vmware.vim25.mo.ServiceInstance;
import java.net.MalformedURLException;
import java.net.URL;
import java.rmi.RemoteException;
import java.util.Arrays;
import java.util.Date;
import java.util.Iterator;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class ParallelRequests {
    public static void main(final String[] args) {
        // Read the args.
        if (args.length < 4) {
            throw new RuntimeException("Usage: firstVCenterAddress secondVCenterAddress user password");
        }
        final Iterator<String> args_ = Arrays.asList(args).iterator();
        final String firstVCenterAddress = args_.next();
        final String secondVCenterAddress = args_.next();
        final String user = args_.next();
        final String password = args_.next();

        try {
            final ExecutorService executor = Executors.newFixedThreadPool(2);
            final Callable<ManagedEntity[]> getVMFromFirstVCenter = () -> getVM(getServiceInstance(firstVCenterAddress, user, password));
            final Callable<ManagedEntity[]> getVMFromSecondVCenter = () -> getVM(getServiceInstance(secondVCenterAddress, user, password));

            for (final Future<ManagedEntity[]> future : executor.invokeAll(Stream.of(getVMFromFirstVCenter, getVMFromSecondVCenter).collect(Collectors.toSet()))) {
                try {
                    System.out.println("Done " + new Date());
                    for (final ManagedEntity managedEntity : future.get()) {
                        System.out.println(managedEntity.getName());
                    }
                } catch (InterruptedException | ExecutionException e) {
                    e.printStackTrace();
                }
            }

            // Wait.
            Thread.sleep(5000L);

            // Stop.
            executor.shutdown();
        } catch (final Exception exception) {
            exception.printStackTrace();
        }
    }

    public static ServiceInstance getServiceInstance(final String address, final String username, final String password)
    throws RemoteException, MalformedURLException {
        return new ServiceInstance(new URL("https", address, -1, "/sdk"), username, password, true);
    }

    public static ManagedEntity[] getVM(final ServiceInstance serviceInstance)
    throws InvalidProperty, RuntimeFault, RemoteException {
        return new InventoryNavigator(serviceInstance.getRootFolder()).searchManagedEntities("VirtualMachine");
    }
}
```

Try to run it multiple times, it depends on when the threads are passing through _TrustAllSSL.getTrustContext()_ method.

Thanks a lot!

**Comment by michaelrice** [comment]
Thanks for the sample. I dont work on this full time like I used to so it will be a little while before I can mock up some tests around it and get to fixing it. If you happen to find the problem and or fix it please be sure to let me know, and if possible patches welcome :)

**Comment by alex-lata** [comment]
Hi,
I was trying to create the branch and the pull request for this issue and, unfortunately, I do not have the rights to do it.  _Permission to yavijava/yavijava.git denied to a-lata._
My fix it is quite simple, I have added 'synchronized' to TrustAllSSL#getTrustContext method.
`public static synchronized SSLContext getTrustContext() throws RemoteException`.

My tests are passing now. Let me know if I can help somehow.

Thanks,
Alex

**Comment by michaelrice** [comment]
Hi @a-lata I have documented the step by step process here: https://github.com/yavijava/yavijava/wiki/Contributing let me know if you need any help.

**Comment by anderssv** [comment]
I'm still seeing this issue in the 6.0.04 release. Any idea?

**Comment by michaelrice** [comment]
@anderssv this issue was reported on 6.0.04 so thats to be expected. The fix is in the gradle branch and there has not been a release since it was submitted, accepted, and merged. The next release Im planning is for 6.5 so if you need the fix sooner you will need to build your own jar using the code currently in the gradle branch.

**Comment by anderssv** [comment]
Oh, ok I didn't get the dates to match up. Thanks for clarifying. :)
