### ISSUE TITLE
changing  annotation needs vm-configuration-settings privilege

### ISSUE THREAD

**Issue by jmdebruin-amc** [yavijava/yavijava#172]
In de web-client, fat-client and vijava2120100824 the only privileges needed to change an annotation is virtual_machine-configurations-set_annotation. In yavijava-6.0.04 one needs virtual_machine-configurations-set_annotation and virtual_machine-configurations-settings. Without the later an permission denied acception is thrown.

piece of the code:

VirtualMachineConfigSpec modification = new VirtualMachineConfigSpec();
            modification.annotation = toHtml(description);
            Task task = vm.reconfigVM_Task(modification);
            task.waitForTask();

**Comment by michaelrice** [comment]
That is not an issue in YAVIJAVA, we just pass the call directly to vCenter. YAVIJAVA does not mangle with permissions in any way. Please check your vCenter permissions and make sure they are correct and that no new policies have been put in place that would prevent this from working.
