### ISSUE TITLE
How to get Site Recovery Manager (SRM) data from vCenter

### ISSUE THREAD

**Issue by zhuminsb** [yavijava/yavijava#180]
Hello experts,
In my project, I want to retrieve SRM data from YAVIJAVA library, does someone know how to get it? which API I will use? I find VMWare has a SRM SDK that you can download from VMWare web site.

Thanks and Regards,

**Comment by michaelrice** [comment]
I havent ever added SRM support to YAVIJAVA so you would need to use some other library to do that.

**Comment by vThinkBeyondVM** [comment]
@michaelrice Similar question I have. If we add vSAN or SRM libraries (SDK released by VMware) into YAVIJAVA eclipse project. it should work together. am I right? vSAN management APIs are released as extension to vSphere Management APIs, hence I was thinking to use vSAN SDK with YAVIJAVA. It should work together. What do you think? What is your suggestion on it?

**Comment by michaelrice** [comment]
@vThinkBeyondVM Ive never used the SRM libraries from vmware before so I have no idea. There is a chance it would work, there is also a chance that the SRM libraries depend on something specific from the vmware vsphere provided library.. Please feel free to try it out and report your success/failures back here so others will have something to refer to when they attempt it.

**Comment by vThinkBeyondVM** [comment]
@michaelrice Ok. I will try and report on success/failure.
