### ISSUE TITLE
Is there vSphere SDK API to perform Storage Array Type Policy(SATP) rule operations?

### ISSUE THREAD

**Issue by yanzhifa** [yavijava/yavijava#183]
Hi,

Is there vSphere SDK API available to perform Storage Array Type Policy(SATP) rule removal and reclaim operation on vCenter Server 6?
I can perform these operations from ESXi console using esxcli commands, but I am not able to figure out how to do it programmatically.
These are the operations that I want to perform:
- esxcli storage nmp satp rule remove
- esxcli storage core claiming reclaim

I just find the QueryStorageArrayTypePolicyOptions method in HostStorageSystem, I do not find any other method the handle SATP rule for LUN operation? 

Any help will be greatly appreciated. Thanks!!

**Comment by michaelrice** [comment]
This isnt a part of the standard vSphere API that this library covers, but it should be possible. I am not sure with out reading which API you would use but this should be part of one of the following 4: 
- vSphere API for Storage Awareness (VASA) 
- vSphere API for Array Integration (VAAI)
- vSphere Storage APIs for Multipathing
- vSphere Storage API for Data Protection

**Comment by michaelrice** [comment]
Also, since it uses esxcli you might be able to use this post: http://www.virtuallyghetto.com/2010/08/hidden-esxcli-apis.html to help you figure out how to use these hidden APIs to make it happen

**Comment by yanzhifa** [comment]
Thanks a lot, @michaelrice , I use the esxcli command line to handle this.

**Comment by michaelrice** [comment]
@yanzhifa if youre open to using ruby there is an esxcli interface in the HostSystem object of rbvmomi [here](https://github.com/vmware/rbvmomi/blob/master/lib/rbvmomi/vim/HostSystem.rb#L4)

**Comment by zhenmie365** [comment]
So, is that said, vSphere Storage API for Data Protection is not include in yavijava of 6.0 version?
Is Using esxcli the only way to use these hidden APIs ?
