### ISSUE TITLE
VirtualDiskManager.createVirtualDisk_Task returns invalid task

### ISSUE THREAD

**Issue by B0bSapp** [yavijava/yavijava#184]
Hello,
We faced problem. Please see code below:

``` java
Datacenter datacenter = (Datacenter) new InventoryNavigator(serviceInstance.getRootFolder()).searchManagedEntity("Datacenter", "dataCenter");
            VirtualDiskManager fileManager = serviceInstance.getVirtualDiskManager();
            FileBackedVirtualDiskSpec vDiskSpec = new FileBackedVirtualDiskSpec();
            vDiskSpec.setAdapterType(VirtualDiskAdapterType.lsiLogic.toString());
            vDiskSpec.setDiskType(VirtualDiskType.thin.toString());
            vDiskSpec.setCapacityKb(1048576);

            Task task = fileManager.createVirtualDisk_Task("[storage-2] storage_volumes/volume.vmdk", datacenter, vDiskSpec);
            try
            {
                task.waitForTask();
            }
            catch (InterruptedException e)
            {
                e.printStackTrace();
            }
            TaskInfo newlyCreatedTask = task.getTaskInfo();
            System.out.println("This is newly created task " + newlyCreatedTask.getKey());
            TaskManager taskManager = serviceInstance.getTaskManager();
            for (Task recentTask : taskManager.getRecentTasks())
            {
                if (task.getMOR().getVal().equals(recentTask.getMOR().getVal()))
                {
                    TaskInfo taskInfo = task.getTaskInfo();
                    System.out.println(taskInfo.getKey());
                }
            }
            System.out.println("Completed searching in recent tasks");
            TaskHistoryCollector taskHistoryCollector = taskManager.createCollectorForTasks(new TaskFilterSpec());
            TaskInfo[] taskInfos;
            while ((taskInfos = taskHistoryCollector.readNextTasks(10)) != null)
            {
                for (TaskInfo taskInfo : taskInfos)
                {
                    if (task.getMOR().getVal().equals(taskInfo.getKey()))
                    {
                        System.out.println(taskInfo.getName());
                    }
                }
            }
            System.out.println("Completed searching in history tasks");

```

Result of execution of this code is NPE, stackTrace is below:

>  Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
>   at com.vmware.vim25.mo.Task.waitForTask(Task.java:182)
>   at com.vmware.vim25.mo.Task.waitForTask(Task.java:132)

If `task.waitForTask()` is removed TaskManager is unable to find this task neither in recentTasks nor via TaskHistoryCollector, looks like task does not exist, but it is not true - vmdk file can be found via client in folder. Can you please help to resolve this issue.
Thanks in advance.

**Comment by michaelrice** [comment]
Can you enable TRACE logging? That may help expose whats going on. If you paste the output please be aware that it will include your passwords and usernames, and IPs and everything so be sure to remove anything like that you dont want to be public.

**Comment by michaelrice** [comment]
Also, please include both your vsphere version and your yavijava version

**Comment by B0bSapp** [comment]
Sorry for keeping silence too long.
[traceLog.txt](https://github.com/yavijava/yavijava/files/513204/traceLog.txt)
Version of yavijava : 6.0.04
Version of vsphere 6.0.0.0 build 2502222.
One moment should be mentioned: this issue is reproduced only when logged in as ordinary user, when admin account is used everything works as it should.

**Comment by michaelrice** [comment]
So it looks like the problem is that you are getting the following:

``` XML
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<soapenv:Body>
<RetrievePropertiesResponse xmlns="urn:vim25"><returnval><obj type="Task">task-17075</obj><missingSet><path>info</path><fault><fault xsi:type="NoPermission"><object type="Folder">group-d1</object><privilegeId>System.Read</privilegeId></fault><localizedMessage/></fault></missingSet></returnval></RetrievePropertiesResponse>
</soapenv:Body>
</soapenv:Envelope>
```

This payload contains a `NoPermission` fault that is not being bubbled up properly. You could work around this issue by making sure your user has `System.Read` for the Folder `group-d1` If you are unsure what Folder that is (its likely a Datacenter) you can use the MOB to explore http://www.virtuallyghetto.com/tag/managed-object-browser 

I will write some tests around the `waitForTask` method so in a future release we will bubble up the exception properly.

**Comment by michaelrice** [comment]
Developer notes for bug fix:

In Task.java lines 186-192 (the try/catch block) if the user does not have permission to view the task object line 187 will always cause a NPE because the task object being returned from the server contains a missing prop set and has a fault in it which needs to be bubbled up.

**Comment by B0bSapp** [comment]
Thank you so much for your response. Other thing I would like to ask: is it possible to prohibit starting such tasks, when you don't have appropriate privileges? Because in this example we were able to start disk creation, but unable to track it's execution

**Comment by michaelrice** [comment]
You should be able to I think. The [AuthorizationManager](http://www.yavijava.com/docs/vim.AuthorizationManager.html) has a few methods in it like `HasPrivilegeOnEntity` and `RetrieveEntityPermissions` that may be helpful for you in finding that info out. You could then place your code in a conditional where if you have the needed access then do this thing...

**Comment by B0bSapp** [comment]
I have one more question, hope it's not too much, I faced following problem: I started couple of tasks (copyVirtualDisk)almost simultanously and immediately tried to search them via TaskHistoryCollector(my application uses yavijava), but for one of them it wasn't successfull, while all the rest were found. I made another attempt, but tried to search via TaskHistoryCollector and in recentTasks too. Result was interesting: all tasks were found in recentTasks, but for TaskHistoryCollector situation was the same (random task was not found). As far as I understand TaskHistoryColletor retrieves taskInfos from VPX_TASK folder, but what about recentTasks? Are they located at the same table? How can this delay be explained? Thanks a lot in advance.

**Comment by mumSky** [comment]
@B0bSapp B0bSapp , have you solved this problem already?
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
at com.vmware.vim25.mo.Task.waitForTask(Task.java:182)
at com.vmware.vim25.mo.Task.waitForTask(Task.java:132)

**Comment by mumSky** [comment]
@michaelrice  What can I do about this question .

**Comment by mumSky** [comment]
@B0bSapp  What can I do about this question

**Comment by michaelrice** [comment]
@mumSky what do you mean?

**Comment by mumSky** [comment]
hi,
I met the problem, but I didn't know how to solve it, so I consulted. 

【
 Caused by: java.lang.NullPointerException
 at com.vmware.vim25.mo.Task.waitForTask(Task.java:218)
】
the code:
【
  try
        {
         TaskInfo info = getTaskInfo();
         tState = info.getState();-------------------this line: the info is null,  why? what can i do for it?
        }
        catch (Exception e)
        {
         Thread.sleep(6000);
          //silently catch 3 exceptions 
          getInfoException=e;
        }
】

thank you .

**Comment by michaelrice** [comment]
@mumSky you need to open your own issue if what has been discussed in this current issue does not apply to your problem.

**Comment by mumSky** [comment]
@michaelrice  This question is similar, so ask how you solved it.
