### ISSUE TITLE
Use mocks in unit tests

### ISSUE THREAD

**Issue by neil-greenwood** [yavijava/yavijava#20]
I'll look into this.

**Comment by neil-greenwood** [comment]
I'm thinking of moving the current tests to src/intTest/java or src/integTest/java.

http://thoughtfulsoftware.wordpress.com/2014/01/26/integration-testing-a-gradle-application/ has some nice ideas.

Any preference on the name?

**Comment by michaelrice** [comment]
IntTest is fine by me. Thanks for your help on this.

**Comment by michaelrice** [comment]
Hi @neil-greenwood hows this coming?

**Comment by neil-greenwood** [comment]
Slowly. I've moved the current tests, since that was quite easy. I'm busy in work which is holding up the creation of new unit tests using mocks.

**Comment by michaelrice** [comment]
@neil-greenwood Can you open a p/r with the changes to the structure? That way I can start working on some more tests as well that will merge cleanly into this new layout.

**Comment by neil-greenwood** [comment]
P/r #26 created.
