### ISSUE TITLE
Alarm reset to green throws error

### ISSUE THREAD

**Issue by asvignesh** [yavijava/yavijava#250]
With the new version YAVIJAVA (6.0.05) am getting 

> Type Mismatch: expected: class Vim::Alarm::AlarmManager, found: class Vpxd::Alarm::AlarmMoImpl

 while trying to reset an alarm "VM Mac address conflict" while attaching VM to inventory from cloned datastore.

```java
final AlarmState[] triggeredAlarmState = _vmobj.getTriggeredAlarmState();
        for (AlarmState alarmState : triggeredAlarmState) {
            final ManagedObjectReference alarmMor = alarmState.getAlarm();

            com.vmware.vim25.mo.Alarm alarmObject = (Alarm) MorUtil.createExactManagedObject(_si.getServerConnection(), alarmMor);
            final AlarmInfo alarmInfo = alarmObject.getAlarmInfo();
            if (alarmInfo.getSystemName().equalsIgnoreCase("alarm.VmMacConflictAlarm")) {

                com.vmware.vim25.mo.AlarmManager alarmManager = new AlarmManager(_si.getServerConnection(), alarmMor);
                alarmManager.setAlarmStatus(alarmObject, _vmobj, "green");
                break;
            }
        }
```

**Comment by asvignesh** [comment]
Even the same alarm from the Datacenter MO also throws exception

![image](https://user-images.githubusercontent.com/2026113/33073539-35b20c24-cee9-11e7-8723-eff0f121efbd.png)

**Comment by michaelrice** [comment]
@asvignesh I asked in the gitter chat a couple of times for you to provide the TRACE level logging but maybe you didnt see the message, so Ill ask here too. Can you provide the TRACE level logging? I wont be able to help you with out it. That logging will contain your password in plain text so please be sure to remove the password before posting the log.

**Comment by asvignesh** [comment]
Sorry didn't see the gitter message.

Error message from vSphere task "The request refers to an unexpected or unknown type."

[trace.txt](https://github.com/yavijava/yavijava/files/1496333/trace.txt)

**Comment by michaelrice** [comment]
Its like there are some missing logs here.. In what you posted there is the stack trace `2017-11-22 19:37:23 ERROR WSClient:99 - Exception caught while invoking method: SetAlarmStatus`
But to get to line 99 it had to go by line 89 https://github.com/yavijava/yavijava/blob/gradle/src/main/java/com/vmware/vim25/ws/WSClient.java#L89 which would mean there is a log statement of `log.trace("Invoking method: " + methodName);` and in this case it would be `Invoking method: SetAlarmStatus` but the only messages in your file about methods being invoked are for `Invoking method: RetrieveProperties` no other messages.

It also has to go past line 90 which would add the payload being sent to the server as well:
https://github.com/yavijava/yavijava/blob/gradle/src/main/java/com/vmware/vim25/ws/SoapClient.java#L240 (this is called on line 90 at via marshall()) and this message is missing.

**Comment by michaelrice** [comment]
After going through your TRACE logs I found the following issue:

https://gist.github.com/michaelrice/fe1a674ad9c7fac180d6a254e813a862#file-thing-xml-L5

As seen on line 5 of that gist the first param is an `Alarm` instance and it should be an `AlarmManager`.  

***Edit***
The `AlarmManager` you are creating in the code you posted above you are using an `Alarm` MOR to make an `AlarmManager` and that is why this is happening. 

```java
com.vmware.vim25.mo.AlarmManager alarmManager = new AlarmManager(_si.getServerConnection(), alarmMor);
```
That is wrong. So that is making an `AlarmManager` but assigning it the MOR of an actual `Alarm`

**Comment by michaelrice** [comment]
Let me know if you have any other issues

**Comment by asvignesh** [comment]
@michaelrice  it works, after changing the AlarmManager initialization from the serviceInstance it is working.
Thanks for your support
