### ISSUE TITLE
After the VM is created, the NIC of the VM cannot be seen on the vCenter.

### ISSUE THREAD

**Issue by lindaosong** [yavijava/yavijava#271]
As the title, I created the virtual machine through the createVM_Task method. I can't see the virtual machine's network card on vCenter, although I have set the network card configuration in VirtualMachineConfigSpec.

Has anyone encountered a similar problem, ask for help, I used vc 6.5

**Comment by michaelrice** [comment]
Im unable to reproduce this. If its still a problem please reopen this and provide some sample code I can use to recreate the problem.
