### ISSUE TITLE
Reconfigure VM for GPU

### ISSUE THREAD

**Issue by santoshbebe** [yavijava/yavijava#273]
Hi, 

With the available APIs in 6.5 support of YAVIJAVA, how can we share a GPU across VM's, is it the same way we add a PCI device config to reconfigure a VM. 

Anyone has tried it earlier. Any pointers or links is much appreciated.

Thanks
Santosh

**Comment by michaelrice** [comment]
I have not completed the 6.5 or newer work yet, so unless its possible with 6.0 it wont be possible to do until the 6.5 work is completed.
