### ISSUE TITLE
Exceptions are not received by the caller

### ISSUE THREAD

**Issue by hubertverstraete** [yavijava/yavijava#28]
Each API call may throw an exception that is defined in the vSphere API reference. But these exceptions are not received by the caller.
I have written a very simple code that tries to login to an ESXi/vCenter server with an unknown user. The expected result is to receive an InvalidLogin exception, but no exception is received.

Until vijava 5.1, I was receiving all exceptions as expected, but in vijava 5.5 beta I had noticed that one exception was received with another identity. I may have missed the fact that it happens for all exceptions since vijava 5.5 beta and therefore the problem may exist before the fork to yavijava. The difference in yavijava is that I don't receive an exception at all.

Environment on CentOS 7:
Oracle JDK 1.7.0_75
yavijava-5.5.07.jar
httpclient-4.3.5.jar
dom4j-1.6.1.jar
log4j-1.2.17.jar

**Comment by hubertverstraete** [comment]
``` java
import java.net.URL;
import com.vmware.vim25.InvalidLogin;
import com.vmware.vim25.mo.ServiceInstance;

public class do_invalid_login
{
    public static void main(String[] args) throws Exception
    {
        String serverDns = args[0];
        String login = "unknown_user";
        String passwd = "password";
        ServiceInstance si = null;

        URL url = new URL("https://" + serverDns + "/sdk");

        try {
            si = new ServiceInstance(url, login, passwd, true);
        }
        catch (InvalidLogin e) {
            System.out.println("Received InvalidLogin exception as expected");
            System.exit(1);
        }
        catch (Exception e) {
            System.out.println("Received another exception: " + e);
            System.exit(1);
        }

        System.out.println("Did not receive an exception. " + si);

        if (si == null) {
            System.out.println("Cannot connect to " + serverDns);
            System.exit(1);
        }

        si.getServerConnection().logout();
    }
}
```

**Comment by michaelrice** [comment]
Which version of java are you using?

-mike

**Comment by hubertverstraete** [comment]
I've edited my first comment while you were sending this mail, please
reload the page.

**Comment by michaelrice** [comment]
I can tell this is going to take some time to fix. There are literally 0 tests around this part of the code. Im looking into how to test it the way its currently implemented but its looking more and more like Im going to have to do a fair bit of refactoring to make this part of the code testable. Ill keep you updated with what I find and try to get a fix out as quickly as I can.

**Comment by michaelrice** [comment]
@hubertverstraete I have a small patch that restores the broken exceptions in vijava 5.5 I was doing some testing and found that vijava 5.5 beta is only throwing a RemoteException when it should be throwing something else. The commit 74e438a restores that. I am going to work on fixing the actual problem this weekend. Before I work on fixing it though I am going to start writing tests around the parser. That way the fix will be easier and I can be confident that the fix doesnt break something else.

**Comment by michaelrice** [comment]
Hi @hubertverstraete 

My latest commit 1cb9066 fixes the issue you reported. Im not going to rush out an update to maven because I still dont have the test coverage I want and I would like to make sure there arent any other issues like this, but please apply the patch and do some tests and let me know how it goes.

**Comment by hubertverstraete** [comment]
Hi Michael,
I've tried with the latest commit and for now it works much much better.
I was able to receive the following exceptions and their arguments:
InvalidPowerState
GuestOperationsUnavailable
InvalidLogin
FileNotFound
FileAlreadyExists

**Comment by michaelrice** [comment]
Thats wonderful! Ill be working on better coverage over the next couple of weeks, and I am currently hoping to release my next update in late March or early April.
