### ISSUE TITLE
Can I specify the ESXi version when creating a virtual machine?

### ISSUE THREAD

**Issue by jian-yang-fit2cloud** [yavijava/yavijava#285]
I want to specify the ESXi version when I clone from vm template, like this:

![image](https://user-images.githubusercontent.com/80813299/135390732-9a7af8a5-f476-4b06-8703-28ee36460395.png)

Is there any way to achieve this?

**Comment by Zybrion** [comment]
In your title you specified "When creating a virtual machine". In this case you can use the following to set the hardware version of the vm:
```
VirtualMachineConfigSpec vmSpec = new VirtualMachineConfigSpec();
vmSpec.setVersion("vmx-19");
```

You can look up the hardware versions here: [here](https://kb.vmware.com/s/article/1003746)

<html><body>


Virtual Hardware Version | Products
-- | --
19 | ESXi 7.0 U2 (7.0.2)
18 | ESXi 7.0 U1 (7.0.1)			Fusion 12.x			Workstation Pro 16.x			Workstation Player 16.x
17 | ESXi 7.0  (7.0.0)
16 | Fusion 11.x			Workstation Pro 15.x			Workstation Player 15.x
15 | ESXi 6.7 U2
14 | ESXi 6.7			Fusion 10.x			Workstation Pro 14.x			Workstation Player 14.x
13 | ESXi 6.5
12 | Fusion 8.x			Workstation Pro 12.x			Workstation Player 12.x
11 | ESXi 6.0			Fusion 7.x			Workstation 11.x			Player 7.x
10 | ESXi 5.5			Fusion 6.x			Workstation 10.x			Player 6.x


</body>
</html>

If you actually mean to clone from a template, then I sadly have not found a way yet. Our solution was to adjusted all templates inside of vcenter to the version we needed.

**Comment by jian-yang-fit2cloud** [comment]
thank you for your reply!
