### ISSUE TITLE
vsphere 6 support

### ISSUE THREAD

**Issue by michaelrice** [yavijava/yavijava#29]
vSphere 6 announced today. Need to add support.

**Comment by LeeTheMC** [comment]
Have you identified any particular issues with vSphere 6?

We are currently having problems with the InventoryNavigator class from ViJava on vSphere 6, and I suspect that something changed on the platform.

So obviously we are looking for alternatives to ViJava...

**Comment by michaelrice** [comment]
Please feel free to try YAVIJAVA and report any bugs. With 6 not being GA
yet I haven't added any specific support for it yet.

**Comment by michaelrice** [comment]
@LeeTheMC I have created https://github.com/michaelrice/yavijava/tree/vsphere_6 to begin development for adding support for 6.0

**Comment by rjtokenring** [comment]
I will have vSphere 6 env RC ready next week. I will try and let you know my results.

**Comment by michaelrice** [comment]
@rjtokenring sounds great. Im having issues with how I normally test which I have raised here: https://communities.vmware.com/message/2481606 so until that is resolved for me Im stuck with what little Ive been able to do thus far.

**Comment by LeeTheMC** [comment]
Can you re-post the message from the community?  It says that I'm not
authorized to view it.  Thanks.

**Comment by michaelrice** [comment]
@LeeTheMC I did some searching and just realized vsphere 6 is still under the NDA terms. I thought since it had been announced and since so many vmware employees have been openly blogging about various bits that the NDA period had ended. That is not the case so due to that I decided to delete the branch I created and Im going to refrain from any further discussion regarding support  for vsphere 6 until it is released as GA or the NDA period ends. I do not want to put myself or employer at any risk of NDA violations. I would like to encourage you to join the beta program https://communities.vmware.com/community/vmtn/vsphere-beta and then the post I made should be available to you.

**Comment by michaelrice** [comment]
@LeeTheMC I think I spotted the problem with the InventoryNavigator you are having. Its looking for the API version to begin with 4 or 5 to use a newer style traversal spec for its property collector, else it will use a very old style one. And since 6 isnt 4 or 5 then its falling back to that old style one.

https://github.com/michaelrice/yavijava/blob/gradle/src/main/java/com/vmware/vim25/mo/InventoryNavigator.java#L80

Ill get this issue fixed once there is a GA release. Ive already got it patched on my local 6 branch.

**Comment by rjtokenring** [comment]
Yes, it is the same problem that I've found! I've seen your message too late and you answered before me on this thread :)

**Comment by michaelrice** [comment]
@LeeTheMC @rjtokenring  I changed the code in the InventoryNavigator that was using the hard coded version inspection looking for version 4 or 5 to pick which TraversalSpec it would generate. It now just check to see if you have version >= 4 and uses the newer style. This makes InventoryNavigator function as expected on version 4.0 and newer. Please feel free to give it a try. Ill be pushing it to public maven next month. It is now in the gradle branch as of 1c9f59121cbea50c9c8587055cfc45fb55f71465

**Comment by michaelrice** [comment]
Hey everyone. I re-pushed my 6.0 branch. Looks like it went GA today.

**Comment by ljader** [comment]
Thx for your work Michael on vSphere 6.
I have one suggestion - your commit 487c7e3f56f should be splitted into two:
a) one which introduces only whitespace changes
b) and second one which fixes things for vSphere 6
Using this aproach it would be easier when using blame with ignoring whitespaces https://coderwall.com/p/x8xbnq

**Comment by michaelrice** [comment]
@ljader thanks for your feedback. Ill try to do that going forward. There is a lot of tabs to spaces changes Ill be making.

**Comment by jaidmoha3** [comment]
IoFilterManager is empty. Could you please add support for it. Thanks a lot.

**Comment by michaelrice** [comment]
Hi @jaidmoha3 I got busy with some work projects the last couple of weeks but should be able to get back to 6.0 support this week sometime. Thanks for your feedback!

**Comment by jaidmoha3** [comment]
Can i take the latest vsphere 6 patch and use it to connect to vsphere server 6.0, to get the basic stuff working?

**Comment by michaelrice** [comment]
You can use 5.5.10 and it will work fine. You just won't get access to the
new managed objects, data objects, methods, and properties.

**Comment by jaidmoha3** [comment]
Ok thanks. i am on VI Java 5.5, the last release. I am planning to move to yavi and use the vsphere 6 , especially the new MO's and data objects.. so will wait for you update on the 6.0. Any timeframe we are looking here for 6.0 support. Thanks and appreciate your help.

**Comment by jaidmoha3** [comment]
Do we have login with certificate available under yavi, this is the login without user session or credentials but with the certificate that we used for vcenter registration

**Comment by michaelrice** [comment]
Its hard to give a time line for this because I only work on it in my free
time. I can say I am actively working on it everyday right now because I
have nothing else pressing to do, but that could change anytime without
much notice.

Getting 6.0 support has not been made a priority for us at work yet so I
can't get anyone else on my team working on this yet in our sprints.

I do welcome pull requests and would love any help anyone is willing to
offer to help get this support done.

If anyone is interested in helping I would be happy to help explain what
needs to be done and start some kind of jira or trello board to track the
work so we don't duplicate efforts.

**Comment by michaelrice** [comment]
I'm not sure. I'll take a look and see. If not I'll create an issue and get
it on the roadmap.

**Comment by jaidmoha3** [comment]
I am interested in helping develop support for 6.0 version

**Comment by jaidmoha3** [comment]
Just to get 6.0 working, we need to change the soapclient api version to 6.0 right ?

**Comment by michaelrice** [comment]
No. To get 6.0 vSphere to work with yavijava all you have to do is use
5.5.10 or newer. And it will "just work" if you want to try any of the new
managed objects I've added support for up to this point you need to use the
vsphere 6 branch

**Comment by jaidmoha3** [comment]
I will pick the vsphere 6 branch , i need the new objects as well.

**Comment by michaelrice** [comment]
Ive created a trello board with tasks of what needs to be done:

https://trello.com/b/cfmXM08Y/yavijava

**Comment by michaelrice** [comment]
@jaidmoha3 about the login you asked about. Do you know the specific method needed for that? Ive never used that type of login personally but based on the docs it seems like you are looking for `loginByToken` which is currently in the code base.

**Comment by jaidmoha3** [comment]
Please assign iofiltermanager and overhead manager to me

Thanks,
Jaidil

**Comment by michaelrice** [comment]
@jaidmoha3 do you have a trello user name? Ill add you to the org so you can pick up the story.

**Comment by jaidmoha3** [comment]
Jaidil Karippara (jaidilkarippara) is my trello user name

**Comment by LeeTheMC** [comment]
Hi Michael.  Thanks for all of your work on vSphere 6.  It is much appreciated.

Have you tried the SessionManager.CloneSession() method at any point?  I'm having issues with it on vSphere 6.  It throws a NotAuthenticated exception when trying to acquire the clone ticket.

**Comment by michaelrice** [comment]
Hi Lee I have never used that method on any version. Would you mind opening
a new issue and include your full stack trace and any logs. It would also
help if you can give me a small sample app that I can run that will
reproduce the problem.

Thanks!

-mike

**Comment by jaidmoha3** [comment]
I have the ioFiltermanager and other classes ready for review.

Please let me know how to proceed for commit /merge/review

Thanks,
Jaidil

**Comment by michaelrice** [comment]
Hi @jaidmoha3 please make sure you have rebased against the vsphere6 branch, then open a pull request against the vsphere6 branch.

If you need any assistance with that feel free to join me on either freenode irc in #vijava or use the gitter chat here: https://gitter.im/yavijava/yavijava

**Comment by michaelrice** [comment]
For those watching this issue for progress there is 1 more existing ManagedObject to add new methods to, and 1 new managed object in review. That puts this pretty close to being done. There is a lot more left that I did not put on the trello board though. There will still be close to 90 existing Dataobjects that have new properties that need to be updated, almost 50 new enums, and over a dozen existing enums that all need to be updated as well. My plan to tackle them is a new project I created called [yavijava_generator](https://github.com/yavijava/yavijava_generator). I plan to use it to generate all DataObjects, Enums, and Faults going forward. This is going to cause a wee bit of mess for those of you tracking the diffs the first time I run it because the change set will be mixed in the white space change. This will only happen on the first run, so sorry in advance for any inconvenience its going to cause you.

**Comment by michaelrice** [comment]
One other thing. I should be cutting my first beta release for 6.0 is about 1 week or so. Stay tuned!

**Comment by jaidmoha3** [comment]
Hi ,
Can we sit together on Tuesday to complete my pull request for iofiltermanager 

Thanks,
Jaidil

**Comment by michaelrice** [comment]
I'm trying to knock these things out before next week because I start a new
job Tuesday. I can't say for sure how much time I will have but I can try.
What time were you wanting to try to meet up?

-mike

**Comment by jaidmoha3** [comment]
am available 9 AM PST - 9 PM PST on tuesday.. Please let me know your
convenience

**Comment by michaelrice** [comment]
@jaidmoha3 Ive got some spare time now. Can you join the gitter chat or freenode irc on #vijava

**Comment by michaelrice** [comment]
Folks as soon as this IOFilterManager code is merged we will be ready for the first beta release!

**Comment by michaelrice** [comment]
OK folks, this thing is ready for a 6.0 beta release. Once I merge this code Im closing this issue and locking it. For any issues you find in the 6.0.01b1 release please open a NEW issue.

**Comment by michaelrice** [comment]
OK,

For those of you who want to test out this new `6.0.01b1` release go to this page:

```
https://github.com/yavijava/yavijava/releases
```

Download the `6.0.01b1.zip` file.
Unzip the file. A directory called yavijava-6.0.01b1 will be created. Enter that directory.
On Linux or Mac use:

```
./gradlew build
```

On Windows use:

```
gradlew.bat build
```

This will build a jar for you. It will be in the `build/libs` directory.
