### ISSUE TITLE
Reuse SSLSocketFactory

### ISSUE THREAD

**Issue by michaelrice** [yavijava/yavijava#38]
http://sourceforge.net/p/vijava/feature-requests/24/

This part of the code has been refactored since this was reported but I dont think its really been fixed. I think its just called another way now.

> WCClient uses a new instance of SSLSocketFactory every time it connects to VC. As a result, sockets cannot be reused. There is also a small performance issue that trustAllHttpsCertificates() is executed upon each connection when it actually needs to be executed only once per the lifetime of the application.
> Suggested code changes:

``` java
private static volatile boolean initialized = false; // new code
private static void trustAllHttpsCertificates() throws NoSuchAlgorithmException, KeyManagementException {
    if (initialized) {return; }// new code
    initialized = true; // new code
    TrustManager[] trustAllCerts = new TrustManager[1]; 
    trustAllCerts[0] = new TrustAllManager(); 
    SSLContext sc = SSLContext.getInstance("SSL"); 
    sc.init(null, trustAllCerts, null); 
    HttpsURLConnection.setDefaultSSLSocketFactory(sc.getSocketFactory());
}
```

**Comment by michaelrice** [comment]
An issue was raised on the vijava forums about the SSL being a global disable. This fix may as well go along with this change. Post for reference: http://sourceforge.net/p/vijava/discussion/826592/thread/33f68590/

**Comment by BigBeaule** [comment]
Hello,

The current fix is correcting the security issue, but not the reuse issue. Each time a request is sent, a new handshaking occurs which really impact the performance if you do a lot of them (around 4 time slower). 

You are reusing the SSLContext but not the SSLSocketFactory which is the important part to use the fast handshaking. Saving the SSLSocketFactory in the constructor and reusing it for each connection seem to solve the issue.

Regards.

**Comment by michaelrice** [comment]
Cool thanks for pointing this out. I'll take another stab at it unless you would like to send a pull request.
