### ISSUE TITLE
new vsphere 6 managed objs have wrong getters and setters

### ISSUE THREAD

**Issue by michaelrice** [yavijava/yavijava#45]
After doing a code review I found that the getters and setters are done incorrectly for the new vsphere 6.0 managed objects I added. The properties need to be adjusted to use getCurrentProperty and friends from the ManagedObject class before they are merged into the gradle branch and released for consumption.

This relates to #29

**Comment by jaidmoha3** [comment]
am getting the following exception during PropertyCollector.retrievePropertiesEx(ClusterResource.)

java.rmi.RemoteException: Exception in SoapClient.invoke:; nested exception is: 
    java.lang.NoSuchFieldException: protocolEndpoint

**Comment by michaelrice** [comment]
@jaidmoha3 It will really help to know what youre doing when you get that. Can you provide the minimal amount of code possible to reproduce the problem?

**Comment by jaidmoha3** [comment]
am upgrading to the GA version of vCenter Server 6.0, i was on a vMware private drop, maybe that is causing the problem.

This is the API am using.

```
/** @since SDK4.1 */
```

  public RetrieveResult retrievePropertiesEx(PropertyFilterSpec[] specSet, RetrieveOptions options) throws InvalidProperty, RuntimeFault, RemoteException
  {
    return getVimService().retrievePropertiesEx(getMOR(), specSet, options);
  }

**Comment by michaelrice** [comment]
@jaidmoha3 Im sorry but you still havent given me anything I can go on here.. Can you please give me some sample code I can run that will reproduce your error?

Just a simple java file with a main class I can compile and run?

**Comment by jaidmoha3** [comment]
java.rmi.RemoteException: Exception in SoapClient.invoke:; nested exception is: 
	java.lang.NoSuchFieldException: maxMemoryFileSize

While trying to collect Cluster level objects, am seeing the noSuchFieldException.. Is it because we haven't implemented the code completely for the 

 @Override
    public ObjectContent[] getObjectsByParentEntitys(ManagedEntity parentEntity, String[][] entityType)
                    throws RemoteExpectedException {
        assert ((parentEntity != null) && (entityType != null));
        final RetrieveOptions options = new RetrieveOptions();
        options.setMaxObjects(DEFAULT_MAX_OBJECT_PROPERTY_COUNT);
        try {
            return this.retrieveObjectContents(parentEntity, entityType, options);
        } catch (final InvalidProperty e) {
            throw new RemoteExpectedException(e);
        } catch (final RuntimeFault e) {
            throw new RemoteExpectedException(e);
        } catch (final RemoteException e) {
            throw new RemoteExpectedException(e);
        }
    }

public static PropertyFilterSpec createExtensionPropertySpec(ManagedEntity extensionManager, String[][] typeinfo) {
        return createPropertySpec(extensionManager, typeinfo, null);
    }

  
    @Override
    public PropertyFilterSpec createInventoryPropertySpec(ManagedEntity parentEntity, String[][] typeinfo) {
        return createPropertySpec(parentEntity, typeinfo, getSelectionSpec());
    }

    public static PropertyFilterSpec createPropertySpec(List<ManagedEntity> parentEnties, String[][] typeinfo) {
        final PropertyFilterSpec spec = new PropertyFilterSpec();
        final PropertySpec[] propspecary = PropertyCollectorUtil.buildPropertySpecArray(typeinfo);
        spec.setPropSet(propspecary);
        for (final ManagedEntity parentEntity : parentEnties) {
            final ObjectSpec os = PropertyCollectorUtil.creatObjectSpec(parentEntity.getMOR(), Boolean.FALSE,
                            getSelectionSpec());
            ObjectSpec[] currentSpec = spec.getObjectSet();
            if (currentSpec == null) {
                currentSpec = new ObjectSpec[] {};
            }
            final ObjectSpec[] newSpec = new ObjectSpec[currentSpec.length + 1];
            for (int i = 0; i < currentSpec.length; i++) {
                newSpec[i] = currentSpec[i];
            }
            newSpec[currentSpec.length] = os;
            spec.setObjectSet(newSpec);
        }
        return spec;
    }

    public static PropertyFilterSpec createPropertySpec(ManagedEntity parentEntity, String[][] typeinfo,
                    SelectionSpec[] sSpecs) {
        final PropertySpec[] propspecary = PropertyCollectorUtil.buildPropertySpecArray(typeinfo);
        final ObjectSpec os = new ObjectSpec();
        os.setObj(parentEntity.getMOR());
        os.setSkip(Boolean.FALSE);
        if (sSpecs != null) {
            os.setSelectSet(sSpecs);
        }

        final PropertyFilterSpec spec = new PropertyFilterSpec();
        spec.setObjectSet(new ObjectSpec[] {
            os
        });
        spec.setPropSet(propspecary);
        return spec;
    }

    private static SelectionSpec[] getSelectionSpec() {
        // Recurse through the folders
        final TraversalSpec visitFolders = PropertyCollectorUtil.createTraversalSpec("visitFolders", "Folder",
                        "childEntity", new String[] {
                            "visitFolders", "dcToHf", "dcToVmf", "crToH", "crToRp", "HToVm", "rpToVm", "DsToH", "crToD"
                        });
        final TraversalSpec vAppToRp = PropertyCollectorUtil.createTraversalSpec("vAppToRp", "VirtualApp",
                        "resourcePool", new String[] {
                            "rpToRp", "vAppToRp"
                        });
        // Recurse through all ResourcePools
        final TraversalSpec rpToRp = PropertyCollectorUtil.createTraversalSpec("rpToRp", "ResourcePool",
                        "resourcePool", new String[] {
                            "rpToRp", "rpToVm"
                        });

        // Recurse through all ResourcePools
        final TraversalSpec rpToVm = PropertyCollectorUtil.createTraversalSpec("rpToVm", "ResourcePool", "vm",
                        new SelectionSpec[] {});

        // Traversal through ResourcePool branch
        final TraversalSpec crToRp = PropertyCollectorUtil.createTraversalSpec("crToRp", "ComputeResource",
                        "resourcePool", new String[] {
                            "rpToRp", "rpToVm"
                        });
        // Traversal through host branch
        final TraversalSpec crToH = PropertyCollectorUtil.createTraversalSpec("crToH", "ComputeResource", "host",
                        new SelectionSpec[] {});

        // Traversal through hostFolder branch
        final TraversalSpec dcToHf = PropertyCollectorUtil.createTraversalSpec("dcToHf", "Datacenter", "hostFolder",
                        new String[] {
                            "visitFolders"
                        });

        // Traversal through vmFolder branch
        final TraversalSpec dcToVmf = PropertyCollectorUtil.createTraversalSpec("dcToVmf", "Datacenter", "vmFolder",
                        new String[] {
                            "visitFolders"
                        });

        final TraversalSpec HToVm = PropertyCollectorUtil.createTraversalSpec("HToVm", "HostSystem", "vm",
                        new String[] {
                            "visitFolders"
                        });

        final TraversalSpec DsToH = PropertyCollectorUtil.createTraversalSpec("DsToH", "HostSystem", "datastore",
                        new String[] {
                            "visitFolders"
                        });
        // Traversal through computer resource branch
        final TraversalSpec crToD = PropertyCollectorUtil.createTraversalSpec("crToD", "ComputeResource", "datastore",
                        new SelectionSpec[] {});

        final SelectionSpec[] sSpecs = new SelectionSpec[11];
        sSpecs[0] = visitFolders;
        sSpecs[1] = vAppToRp;
        sSpecs[2] = crToH;
        sSpecs[3] = dcToHf;
        sSpecs[4] = dcToVmf;
        sSpecs[5] = rpToRp;
        sSpecs[6] = rpToVm;
        sSpecs[7] = crToRp;
        sSpecs[8] = HToVm;
        sSpecs[9] = DsToH;
        sSpecs[10] = crToD;
        return sSpecs;
    }

/**
     * @param vCenterServer
     * @param userName
     * @param password
     * @throws ExpectedException
     */
    public VsphereSDKHandlerImpl(String vCenterServer, String userName, String password) throws ExpectedException {
        assert (vCenterServer != null);
        assert ((userName != null) && !userName.isEmpty());
        int retry = 0;
        do {
            try {
                final URL url = new URL("https", vCenterServer, "/sdk");
                this.si = new ServiceInstance(url, userName, password, true);
                this.vCenterServer = vCenterServer;
                this.userName = userName;
                break;
            } catch (final MalformedURLException e) {
                throw new ExpectedException(MessageCatalog.MALFORMED_URL);
            } /*catch (final HttpRedirectionException e) {
                throw new RemoteExpectedException(MessageCatalog.HTTP_NOT_ENABLED_BY_SERVER, e);
            } */catch (final com.vmware.vim25.InvalidLogin e) {
                throw new ExpectedException(MessageCatalog.INVALID_LOGIN_CREDENTIALS);
            } catch (final RemoteException e) {
                if ((e.getCause() instanceof java.net.UnknownHostException)
                                || ((e.detail != null) && ((e.detail instanceof java.net.NoRouteToHostException) || (e.detail instanceof java.net.ConnectException)))) {
                    throw new ExpectedException(MessageCatalog.UNKNOWN_VCENTER_HOST);
                } else {
                    logger.warn("Caught RemoteException", e);
                    logger.debug("Retry count = " + retry);
                    retry++;
                    if (retry >= MAX_RETRY) {
                        logger.error("Still failing after retry", e);
                        throw new RemoteExpectedException(MessageCatalog.LOGIN_ERROR, e);
                    }
                    try {
                        Thread.sleep(WAIT_IN_MILISECONDS);
                    } catch (final InterruptedException ignore) {
                    }
                }
            }
        } while (retry < MAX_RETRY);
    }

    /**
     * @param vCenterServer
     * @param sessionId
     * @throws ExpectedException
     */
    public VsphereSDKHandlerImpl(String vCenterServer, String sessionId) throws ExpectedException {
        assert (vCenterServer != null);
        assert ((sessionId != null) && !sessionId.isEmpty());
        int retry = 0;
        do {
            try {
                final URL url = new URL("https", vCenterServer, "/sdk");
                // "vmware_soap_session=\"B3240D15-34DF-4BB8-B902-A844FDF42E85\""
                final String sessionStr = "vmware_soap_session=\"" + sessionId + "\"";
                this.si = new ServiceInstance(url, sessionStr, true);
                this.vCenterServer = vCenterServer;
                final ServerConnection sc = this.si.getServerConnection();
                final Extension[] List = sc.getServiceInstance().getExtensionManager().getExtensionList();
                assert (List != null);
                assert (sc != null);
                if ((sc.getServiceInstance() == null) || (sc.getServiceInstance().getSessionManager() == null)) {
                    logger.warn("getUserSession() returns null");
                    logger.debug("Retry count = " + retry);
                    retry++;
                    if (retry >= MAX_RETRY) {
                        logger.error("Still failing after retry");
                        throw new ExpectedException(MessageCatalog.INVALID_SESSION);
                    }
                    try {
                        Thread.sleep(WAIT_IN_MILISECONDS);
                    } catch (final InterruptedException ignore) {
                    }
                } else {
                    this.userName = sc.getUsername();
                    break;
                }
            } /*catch (final HttpRedirectionException e) {
                throw new RemoteExpectedException(MessageCatalog.HTTP_NOT_ENABLED_BY_SERVER, e);
            } */catch (final MalformedURLException e) {
                throw new ExpectedException(MessageCatalog.MALFORMED_URL);
            } catch (final RemoteException e) {
                if ((e.getCause() instanceof java.net.UnknownHostException)
                                || ((e.detail != null) && ((e.detail instanceof java.net.NoRouteToHostException) || (e.detail instanceof java.net.ConnectException)))) {
                    throw new ExpectedException(MessageCatalog.UNKNOWN_VCENTER_HOST);
                } else {
                    logger.warn("Caught RemoteException", e);
                    logger.debug("Retry count = " + retry);
                    retry++;
                    if (retry >= MAX_RETRY) {
                        logger.error("Still failing after retry", e);
                        throw new ExpectedException(MessageCatalog.INVALID_SESSION);
                    }
                    try {
                        Thread.sleep(WAIT_IN_MILISECONDS);
                    } catch (final InterruptedException ignore) {
                    }
                }
            }
        } while (retry < MAX_RETRY);
    }

**Comment by michaelrice** [comment]
ClusterEVCManager is one of the culprits here.

**Comment by michaelrice** [comment]
This was fixed by 2840908
