### ISSUE TITLE
Question: List all Datastore Clusters (StoragePod) available 

### ISSUE THREAD

**Issue by saamalik** [yavijava/yavijava#53]
How do I retrieve list of all Datastore Clusters which are attached to ALL hosts of a specific ESX cluster?

For instance, given an ESX Cluster Fooo (ClusterComputeResource), I want list all Datastore Clusters (StoragePod) that are connected to EVERY host in an ESX cluster.

My initial naive attempt was as follows:

``` java
            Map<String, ManagedEntity> storages = new LinkedHashMap<>();

            // Datastores Clusters
            ClusterComputeResource ccr = (ClusterComputeResource) cluster;
            Datastore[] datastores = ccr.getDatastores();
            for (Datastore datastore : datastores) {
                if (datastore.getParent() instanceof StoragePod) {
                    StoragePod storagePod = (StoragePod) datastore.getParent();
                    storages.put(storagePod.getName(), storagePod);
                }

            }

```

The problem with the above is that ClusterComputeResource.getDatastores() returns an aggregate of all datastores connected to the hosts in the cluster; but that doesn't necessarily mean that ALL hosts in the cluster have the datastore mounted.

Any ideas?

**Comment by michaelrice** [comment]
Hi @saamalik not sue how I missed this. What do you mean by `but that doesn't necessarily mean that ALL hosts in the cluster have the datastore mounted.`

**Comment by saamalik** [comment]
Hi @michaelrice,
For instance imagine the following:
- Datastore Cluster A
  - Datastore 1
- Datastore Cluster B
  - Datastore 2
- ESX Cluster Foo
  - Host A (DS 1)
  - Host B (DS 1, DS 2)

If the user selects ESX Cluster Foo, then since both hosts A & B have DS 1 mounted, then Datastore Cluster A should be listed as an available DSC Cluster. However DSC B should _not_ be listed since Host A does not mount DS 2.

**Comment by michaelrice** [comment]
Hi @saamalik,

I created a [sample](https://github.com/michaelrice/yavijava_cluster_prop_example) a couple of days ago that may help you here. It gets info about a given cluster using property collectors. You would need to expand upon it though. You would want to add properties like `datastore` to the HostSystem properties. Then you would want to add Datastore the way HostSystem and VirtualMachine have been aded and add properties too for the Datastore like `name`. Once you have that done it would be up to you to relate those objects it returns but it would give you what you're after in a way that will scale no matter how large your inventory became.

I will admit it is going to seem like more work than what you've done so far but if your way did work on a small cluster it would start getting slow on very large inventories. Property Collectors are much harder but they are the only way to make the code fast and scaleable.

**Comment by saamalik** [comment]
Thanks for the response @michaelrice. Ok, I'll give it a go. Thanks.

**Comment by michaelrice** [comment]
Im going to close this issue out since I havent heard anything else. If you need additional assistance please feel free to reopen.
