### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by shubhamrajvanshi** [yavijava/yavijava#54]
Is there a way to get Mor to an object instead of getting it through the invetorybrowser object. Sorry don't know where to post questions for this and this project looked it's active

**Comment by michaelrice** [comment]
I'm not sure what you mean by this. Can you give me an example using the
inventory navigator of what you're doing?

Also this is the right place to ask questions. I have a label I'll tag the
issue with for questions.

-mike

**Comment by shubhamrajvanshi** [comment]
Is there any alternative to this:
VirtualMachine vm = (VirtualMachine) new InventoryNavigator(
                    rootFolder).searchManagedEntity("VirtualMachine", vmname);

can't i do something like:
ServiceInstance si = new ServiceInstance(options);
si.getrooFolder().getMor().setType("VirtualMachine ");

and then set it to a particular VM

**Comment by michaelrice** [comment]
I feel like youre trying to do something specific and think that using the moref is the right thing to do.. which normally isnt right. Would you mind elaborating on what your really trying to do? If youre trying to find a specific VirtualMachine by avoiding the InventoryNavigator there are several ways to do that and they do not involve needing to mess with the moref at all..

**Comment by shubhamrajvanshi** [comment]
I want to find a vm by passing the vmname to the function. Then perform operations like poweron, poweroff and get details about VM. During my old project I did by finding it through inventorynavigator but don't think it's the right way. If there's a better way to do it then it would help.

I am basically calling vijavaapi using Spring. I have been successful to get ServiceInstance bean but don't know how to proceed further

**Comment by shubhamrajvanshi** [comment]
Idea is to implement a IaaS solution using vmware infrastructure. This is one of my academic project but it would be nice implement and say :P

**Comment by michaelrice** [comment]
OK I figured as much. You really dont want to mess with the moref to do this. Also depending on the size of your environment and stuff you really might want to consider using something other than the name. Name is not unique within the vCenter, or even the same Datacenter. I highly recommend using the instance uuid. The instance uuid is the _only_ thing you can count on being unique in the vCenter. Another option is to use findByInventoryPath which will be unique but it does require you to know the full path including all folders to where the VM is stored..

That being said you will want to use the serviceInstance to obtain the searchIndex then use one of the findByXX methods: http://vijava.sourceforge.net/vSphereAPIDoc/ver51/ReferenceGuide/vim.SearchIndex.html

**Comment by michaelrice** [comment]
Hi @shubhamrajvanshi Im going to go ahead and close this issue out. If you still need more help regarding it please feel free to reopen it.
