### ISSUE TITLE
In yavijava-6.0.01b1 capacityInBytes of VirtualDisk should be Long

### ISSUE THREAD

**Issue by hubertverstraete** [yavijava/yavijava#90]
In the data class VirtualDisk, capacityInBytes appeared in vSphere 5.5 as a Long (the object) because it may or may not be set. Unfortunately, in the vSphere 6 branch of yavijava, capacityInBytes is now a long and therefore must always have a value.
Here is a link to the v6 doc: http://pubs.vmware.com/vsphere-60/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.vm.device.VirtualDisk.html

**Comment by michaelrice** [comment]
Hi @hubertverstraete thanks for the report. Ive fixed this issue in [yavijava_generator/18](https://github.com/yavijava/yavijava_generator/pull/18) and will rerun the generator this afternoon and cut a new beta release when thats done. 

These are all the files suffering from this bug:

``` DatastoreInfo.java:
DvsHostInfrastructureTrafficResourceAllocation.java:
DvsVmVnicResourceAllocation.java:
DvsVnicAllocatedResource.java:
HbrManagerVmReplicationCapability.java:
HostPnicNetworkResourceInfo.java:
VMwareIpfixConfig.java:
VRPEditSpec.java:
VirtualDisk.java:
VirtualEthernetCardResourceAllocation.java:
VirtualMachineBootOptions.java:
VirtualMachineConfigInfo.java:
VirtualMachineConfigSpec.java:
VirtualMachineDatastoreInfo.java:
VirtualMachineFileLayoutExFileInfo.java:
VirtualMachineRuntimeInfo.java:
VirtualMachineVMCIDevice.java:
VirtualMachineVMCIDeviceFilterSpec.java:
VirtualMachineVMCIDeviceOptionFilterSpecOption.java:
VirtualMachineVideoCard.java:
VirtualResourcePoolSpec.java:
VirtualVideoCardOption.java:
VrpResourceAllocationInfo.java:
VsanPolicyCost.java:
```

**Comment by michaelrice** [comment]
@hubertverstraete I've cut a 6.0.01b2 release: https://github.com/yavijava/yavijava/releases/tag/6.0.01b2 Thanks again for reporting this!
