### ISSUE TITLE
In yavijava-6.0.01b2 some arrays of long became arrays of Long

### ISSUE THREAD

**Issue by hubertverstraete** [yavijava/yavijava#93]
VirtualMachineConfigSpec and VirtualMachineConfigInfo both have the properties npivPortWorldWideName and npivNodeWorldWideName. Their type was and should be long[] but with the fix of issue #90 this became Long[].

**Comment by michaelrice** [comment]
Hello @hubertverstraete what makes you think they should be `long[]` vs `Long[]`? The documentation for those properties have a \* next to them indicating "Need not be set" 

``` XML
<element name="npivNodeWorldWideName" type="xsd:long" minOccurs="0" maxOccurs="unbounded"/>
<element name="npivPortWorldWideName" type="xsd:long" minOccurs="0" maxOccurs="unbounded"/>
```

The minOccurs=0 means it doesnt have to be set.

**Comment by hubertverstraete** [comment]
Hi Mike

Well, first of all, this has always been an array of long in all versions
of vijava. So for the backward compatibility,  it should continue to be
like this.
Secondly, the "need not to be set" applies to the array. This means you can
have an array of long (new long [3]) or null.

Regards,
Hubert

**Comment by michaelrice** [comment]
Hi @hubertverstraete 

So then because this:

``` java
        long[] mylongArray = null; // this is allowed and valid
        long mylong = null; // this is not so it must be a Long
```

**Comment by hubertverstraete** [comment]
I also looked at some arrays of int in vijava and they are really arrays of int not of Int.
Now, if yavijava is a drop in replacement for vijava, there's not much to discuss :)

**Comment by michaelrice** [comment]
@hubertverstraete I have made the required changes to yavijava_generator and will run it again and replace the required files. I really appreciate your help finding these issues!

**Comment by michaelrice** [comment]
I have cut a 6.0.01b3 release. You can get it here: https://github.com/yavijava/yavijava/releases/tag/6.0.01b3

**Comment by hubertverstraete** [comment]
Thanks, this works.

**Comment by michaelrice** [comment]
@hubertverstraete Thanks for the help finding and reporting this stuff!
